[package]
name = "frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
gloo-net = "0.5"
leptos = { version = "0.6", features = ["csr"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
wasm-bindgen-futures = "0.4"
